# This is a basic workflow to help you get started with Actions
name: Sample_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build API
        run: |
          echo "Building API..."
          sleep 5

  test:
    runs-on: ubuntu-latest
    needs: build-api
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          echo "Running tests..."
          sleep 3

  build-db:
    runs-on: ubuntu-latest
    needs: build-api
    steps:
      - name: Setup Database
        run: |
          echo "Building Database..."
          
  deploy:
    runs-on: ubuntu-latest
    needs: build-db
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          sleep 3
